name: Build
on: [workflow_dispatch, push]

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-11-jdk python3 python3-dev build-essential libstdc++6
          sudo apt-get install aidl
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade Cython buildozer

      # Step 3: Compile for Android
      - name: Build with Buildozer
        run: |
          buildozer android debug

      # Step 4: Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: bin/*.apk
